//! Forces ts-rs to emit src/types/ipc.generated.ts during `cargo test`.
//!
//! ts-rs 9 does not concatenate multiple `#[ts(export)]` derives that share
//! an `export_to` path: each auto-generated test races and overwrites the
//! file. Instead, we drop `export` from the derives and write the file
//! ourselves by composing each type's `decl()` into a single output.

use claude_conductor_lib::accounts::{Account, OauthAccountInfo};
use claude_conductor_lib::context_status::ContextStatus;
use claude_conductor_lib::ipc::accounts::{
    AccountIdentity, AccountsSetupPromptState, AddAccountSession, LoginCheckOutcome,
};
use claude_conductor_lib::ipc::ai_todos::AiTodoEntry;
use claude_conductor_lib::ipc::servers::ServerInfo;
use claude_conductor_lib::ipc::git::GitInfo;
use claude_conductor_lib::ipc::files::TextFileData;
use claude_conductor_lib::ipc::schedule::ExternalScheduledJob;
use claude_conductor_lib::notifications::piper::{PiperStatus, VoiceEntry};
use claude_conductor_lib::sessions::kinds::InstanceKind;
use claude_conductor_lib::sessions::scheduled_items::{
    Recurrence, RecurrenceRule, ScheduledItem, ScheduledKind, ScheduledStatus,
};
use claude_conductor_lib::skill_usage::types::{
    InstalledSkill, InvocationCounts, InvocationSource, SkillDetail, SkillUsageEntry,
    SkillUsageEvent, SkillUsageWeek, TokenBreakdown,
};
use claude_conductor_lib::ipc::storage::{DatasetId, DatasetInfo};
use claude_conductor_lib::slash::{SlashEntry, SlashSource};
use claude_conductor_lib::storage::{RetentionPolicies, RetentionPolicy};
use claude_conductor_lib::tokens::record::{BackfillResult, TokenRecord};
use claude_conductor_lib::types::*;
use claude_conductor_lib::when_done::{ProtocolPhase, ProtocolState, TerminalAction};
use tauri_kit_audio::AudioOutputDevice;
use std::fs;
use std::path::PathBuf;
use ts_rs::TS;

const HEADER: &str = "// This file is auto-generated by `cargo test --test export_types`.\n// Do not edit manually.\n\n";

fn output_path() -> PathBuf {
    // Manifest dir is src-tauri/. Same relative target as the `export_to`
    // attribute on each type so downstream tooling sees a stable path.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("..").join("src").join("types").join("ipc.generated.ts")
}

fn decl<T: TS + 'static + ?Sized>() -> String {
    format!("export {}\n", T::decl())
}

#[test]
fn emit_ipc_types() {
    let mut out = String::from(HEADER);

    // usage
    out.push_str(&decl::<UsageSnapshot>());
    out.push_str(&decl::<WindowUsage>());
    out.push_str(&decl::<ExtraUsage>());

    // project
    out.push_str(&decl::<CharacterWhitelist>());
    out.push_str(&decl::<Avatar>());
    out.push_str(&decl::<ProjectsSortBy>());
    out.push_str(&decl::<ProjectConfig>());
    out.push_str(&decl::<Instance>());
    out.push_str(&decl::<ProjectGroup>());

    // automation
    out.push_str(&decl::<AutomationConfig>());
    out.push_str(&decl::<InstanceKind>());
    out.push_str(&decl::<EndReason>());
    out.push_str(&decl::<AuthState>());
    out.push_str(&decl::<ChannelStatus>());

    // storage / retention (referenced by Settings + storage IPC)
    out.push_str(&decl::<RetentionPolicy>());
    out.push_str(&decl::<RetentionPolicies>());
    out.push_str(&decl::<DatasetId>());
    out.push_str(&decl::<DatasetInfo>());

    // notifications (settings module)
    out.push_str(&decl::<AutoUpdateMode>());
    out.push_str(&decl::<Settings>());

    // multi-account (milestone 01: identity, profile dirs, add-account wizard)
    out.push_str(&decl::<OauthAccountInfo>());
    out.push_str(&decl::<Account>());
    out.push_str(&decl::<AddAccountSession>());
    out.push_str(&decl::<LoginCheckOutcome>());
    out.push_str(&decl::<AccountIdentity>());
    out.push_str(&decl::<AccountsSetupPromptState>());

    // misc IPC
    out.push_str(&decl::<GitInfo>());
    out.push_str(&decl::<TextFileData>());
    out.push_str(&decl::<AiTodoEntry>());
    out.push_str(&decl::<ServerInfo>());
    out.push_str(&decl::<ContextStatus>());

    // tokens
    out.push_str(&decl::<TokenRecord>());
    out.push_str(&decl::<BackfillResult>());

    // token drain (per-chat cost + leaderboard)
    out.push_str(&decl::<claude_conductor_lib::tokens::MessageDrain>());
    out.push_str(&decl::<claude_conductor_lib::tokens::ChatDrain>());
    out.push_str(&decl::<claude_conductor_lib::ipc::DrainBoard>());

    // piper
    out.push_str(&decl::<VoiceEntry>());
    out.push_str(&decl::<PiperStatus>());

    // audio
    out.push_str(&decl::<AudioOutputDevice>());

    // chat (Path C chat hub)
    out.push_str(&decl::<ChatEvent>());
    out.push_str(&decl::<ContentBlock>());
    out.push_str(&decl::<HistoryEntry>());
    out.push_str(&decl::<HistoryPage>());

    // news
    out.push_str(&decl::<NewsPost>());

    // slash autocomplete
    out.push_str(&decl::<SlashEntry>());
    out.push_str(&decl::<SlashSource>());

    // skill usage
    out.push_str(&decl::<InvocationSource>());
    out.push_str(&decl::<TokenBreakdown>());
    out.push_str(&decl::<SkillUsageEvent>());
    out.push_str(&decl::<InvocationCounts>());
    out.push_str(&decl::<SkillUsageEntry>());
    out.push_str(&decl::<SkillUsageWeek>());
    out.push_str(&decl::<SkillDetail>());
    out.push_str(&decl::<InstalledSkill>());

    // when-done protocol (sleep/shutdown when all sessions idle)
    out.push_str(&decl::<TerminalAction>());
    out.push_str(&decl::<ProtocolPhase>());
    out.push_str(&decl::<ProtocolState>());

    // scheduling (scheduled messages / scheduled new-chats)
    out.push_str(&decl::<ScheduledKind>());
    out.push_str(&decl::<RecurrenceRule>());
    out.push_str(&decl::<Recurrence>());
    out.push_str(&decl::<ScheduledStatus>());
    out.push_str(&decl::<ScheduledItem>());
    out.push_str(&decl::<ExternalScheduledJob>());

    let path = output_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dir for ipc.generated.ts");
    }
    fs::write(&path, out).expect("write ipc.generated.ts");
}
