//! Forces ts-rs to emit src/types/ipc.generated.ts during `cargo test`.
//!
//! ts-rs 9 does not concatenate multiple `#[ts(export)]` derives that share
//! an `export_to` path: each auto-generated test races and overwrites the
//! file. Instead, we drop `export` from the derives and write the file
//! ourselves by composing each type's `decl()` into a single output.

use claude_usage_tauri_lib::ipc::misc::GitInfo;
use claude_usage_tauri_lib::notifications::piper::{PiperStatus, VoiceEntry};
use claude_usage_tauri_lib::sessions::kinds::InstanceKind;
use claude_usage_tauri_lib::tokens::record::{BackfillResult, TokenRecord};
use claude_usage_tauri_lib::types::*;
use std::fs;
use std::path::PathBuf;
use ts_rs::TS;

const HEADER: &str = "// This file is auto-generated by `cargo test --test export_types`.\n// Do not edit manually.\n\n";

fn output_path() -> PathBuf {
    // Manifest dir is src-tauri/. Same relative target as the `export_to`
    // attribute on each type so downstream tooling sees a stable path.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("..").join("src").join("types").join("ipc.generated.ts")
}

fn decl<T: TS + 'static + ?Sized>() -> String {
    format!("export {}\n", T::decl())
}

#[test]
fn emit_ipc_types() {
    let mut out = String::from(HEADER);

    // usage
    out.push_str(&decl::<UsageSnapshot>());
    out.push_str(&decl::<WindowUsage>());
    out.push_str(&decl::<ExtraUsage>());

    // project
    out.push_str(&decl::<Avatar>());
    out.push_str(&decl::<ProjectsSortBy>());
    out.push_str(&decl::<ProjectConfig>());
    out.push_str(&decl::<Instance>());
    out.push_str(&decl::<ProjectGroup>());

    // automation
    out.push_str(&decl::<AutomationConfig>());
    out.push_str(&decl::<InstanceKind>());
    out.push_str(&decl::<EndReason>());
    out.push_str(&decl::<AuthState>());
    out.push_str(&decl::<ChannelStatus>());

    // notifications (settings module)
    out.push_str(&decl::<DisplayMode>());
    out.push_str(&decl::<AutoUpdateMode>());
    out.push_str(&decl::<Settings>());

    // misc IPC
    out.push_str(&decl::<GitInfo>());

    // tokens
    out.push_str(&decl::<TokenRecord>());
    out.push_str(&decl::<BackfillResult>());

    // piper
    out.push_str(&decl::<VoiceEntry>());
    out.push_str(&decl::<PiperStatus>());

    // audio
    out.push_str(&decl::<AudioOutputDevice>());

    // chat (Path C chat hub)
    out.push_str(&decl::<ChatEvent>());
    out.push_str(&decl::<ContentBlock>());
    out.push_str(&decl::<HistoryEntry>());
    out.push_str(&decl::<HistoryPage>());

    // news
    out.push_str(&decl::<NewsPost>());

    let path = output_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dir for ipc.generated.ts");
    }
    fs::write(&path, out).expect("write ipc.generated.ts");
}
