// Typed wrapper around the active transport (see ./transport).
// Uses types generated by ts-rs in src/types/ipc.generated.ts.
//
// `invoke` is kept as the project-wide request/response entry point so the
// dozens of existing call sites stay untouched; it now delegates to the active
// transport (Tauri IPC on desktop, HTTP on the future PWA) instead of calling
// Tauri directly. The ambient Window.__TAURI__ declaration lives here because
// TauriTransport (in ./transport) references it.

import { getTransport } from "./transport";

declare global {
  interface Window {
    __TAURI__?: {
      core?: {
        invoke?: <T>(cmd: string, args?: Record<string, unknown>) => Promise<T>;
      };
      event?: {
        listen?: <T>(
          event: string,
          cb: (payload: { payload: T }) => void,
        ) => Promise<() => void>;
        emit?: (event: string, payload?: unknown) => Promise<void>;
      };
    };
  }
}

export async function invoke<T>(
  command: string,
  args?: Record<string, unknown>,
): Promise<T> {
  return getTransport().call<T>(command, args);
}
