// Typed wrapper around @tauri-apps/api's invoke().
// Uses types generated by ts-rs in src/types/ipc.generated.ts.

declare global {
  interface Window {
    __TAURI__?: {
      core?: {
        invoke?: <T>(cmd: string, args?: Record<string, unknown>) => Promise<T>;
      };
    };
  }
}

export async function invoke<T>(
  command: string,
  args?: Record<string, unknown>,
): Promise<T> {
  const core = window.__TAURI__?.core;
  if (!core?.invoke) {
    throw new Error(
      "Tauri runtime not available. Are you running via `cargo tauri dev` or a packaged build?",
    );
  }
  return core.invoke<T>(command, args);
}
