pub mod usage;
pub mod settings;
pub mod projects;
pub mod project_groups;
pub mod project_icons;
pub mod channels;
pub mod chat;
pub mod tokens;
pub mod drain;
pub mod auth;
pub mod audio_preview;
pub mod misc;
pub mod git;
pub mod ai_todos;
pub mod models;
pub mod window;
pub mod update;
pub mod characters;
pub mod audio;
pub mod news;
pub mod slash;
pub mod files;
pub mod skill_usage;
pub mod storage;
pub mod remote_access;

pub use usage::*;
pub use settings::*;
pub use projects::*;
pub use project_groups::*;
pub use project_icons::*;
pub use channels::*;
pub use chat::*;
pub use tokens::*;
pub use drain::*;
pub use auth::*;
pub use audio_preview::*;
pub use misc::*;
pub use git::*;
pub use ai_todos::*;
pub use models::*;
pub use window::*;
pub use update::*;
pub use characters::*;
pub use audio::*;
pub use news::*;
pub use slash::*;
pub use files::*;
pub use skill_usage::*;
pub use storage::*;
pub use remote_access::*;

// Re-export test helper submodules so integration tests can reach them via
// `claude_conductor_lib::ipc::projects_test_helpers` and
// `claude_conductor_lib::ipc::legacy_import_test_helpers`.
pub use projects::projects_test_helpers;
pub use projects::legacy_import_test_helpers;
