//! Chat IPC commands (daemon-backed).
//!
//! Split into focused submodules:
//! - `run`        — per-turn execution: `start_session`, `send_message`,
//!                  `cancel_turn`, `blocks_to_prompt_text`. All turns run in
//!                  the detached daemon via RPC.
//! - `attachments`— image attachments: `paste_image`, `read_attachment`,
//!                  shared `validate_session_id` + `write_attachment` helpers.
//! - `history`    — read-only transcript replays: `load_history`,
//!                  `load_history_page`, `list_history`.
//! - `lifecycle`  — AppHandle / process-tree side: `gc_attachments`,
//!                  `takeover_manual`, `detach_window`, `reattach_window`,
//!                  `respond_permission`, `respond_question`.
//!
//! All `#[tauri::command]` items are re-exported here so the parent
//! `ipc.rs` `pub use chat::*;` keeps surfacing the existing
//! `ipc::<command>` shape used by `lib.rs` `invoke_handler!`.

pub mod attachments;
pub mod builtins;
pub mod daemon_bridge;
pub mod history;
pub mod lifecycle;
pub mod run;
pub mod watcher;

// Glob re-exports so the `__cmd__<name>` symbols generated by
// `#[tauri::command]` are reachable via `crate::ipc::chat::<cmd>` (and via
// the parent `ipc.rs` `pub use chat::*;`). A named `pub use foo::bar`
// re-exports `bar` only; the macro-generated sibling stays hidden.
pub use attachments::*;
pub use builtins::*;
pub use history::*;
pub use lifecycle::*;
pub use run::*;
pub use watcher::*;
